env:
  browser: true
  node: true
  es6: true
extends:
  - "closure-base"
  - "closure-es6"
  - "google"
plugins:
  - "closure"
  - "closure-library"
rules:
  closure-library/no-deprecated-apis: error
  closure-library/prefer-native-array-methods: error
  closure/camelcase:
    - ERROR
    - allowVarArgs: false
      allowOptPrefix: false
      allowLeadingUnderscore: true
      allowTrailingUnderscore: true
      checkObjectProperties: false
  closure/indent: error
  closure/inline-comment-spacing: error
  closure/jsdoc: error
  closure/no-undef: error
  closure/no-unused-expressions: error
  closure/no-unused-vars: error
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
  sourceType: module
